import type { Book } from "../types/book"

export const books: Book[] = [
  {
    id: 1,
    title: "THE GLOWUP MASTERY GUIDE",
    author: "TheSmartStoriesYT",
    description: "A comprehensive guide to mastering self-discipline and communication skills.",
    originalPrice: 2150,
    currentPrice: 299,
    image: "https://envs.sh/mzw.jpg",
    backCover: "https://envs.sh/mzq.jpg",
    type: "Featured",
    rating: 4.5,
    reviews: 50,
    features: [
      "Master self-discipline techniques",
      "Improve communication skills",
      "Boost personal growth",
      "Develop a growth mindset",
    ],
    paymentLink: "upi://pay?pa=paytmqr281005050101159pz7btupdg@paytm&pn=TAPASHI%20ROY&am=299&cu=INR",
  },
  {
    id: 2,
    title: "THE ULTIMATE INSTAGRAM GROWTH GUIDE",
    author: "TheSmartStoriesYT",
    description: "Master Instagram growth strategies and algorithms.",
    originalPrice: 4150,
    currentPrice: 199,
    image: "https://envs.sh/mzW.jpg",
    backCover: "https://envs.sh/mz0.jpg",
    type: "New",
    rating: 4.5,
    reviews: 50,
    features: [
      "Understand Instagram algorithms",
      "Create engaging content",
      "Grow your followers organically",
      "Monetize your Instagram account",
    ],
    paymentLink: "upi://pay?pa=paytmqr281005050101159pz7btupdg@paytm&pn=TAPASHI%20ROY&am=199&cu=INR",
  },
  {
    id: 3,
    title: "PRO GROWTH BUNDLE",
    author: "TheSmartStoriesYT",
    description:
      "Get 130+ GB OF Premium and High Quality Digital Products. The Ultimate Digital Products Bundle. Get bundle of premium masterclasses and ebooks.",
    originalPrice: 9999,
    currentPrice: 99,
    image: "https://envs.sh/mA8.jpg",
    backCover: "https://envs.sh/mzB.jpg",
    type: "Ultimate Digital Products Bundle",
    rating: 4.8,
    reviews: 120,
    specialOffer: "⚡ Get Everything at ₹99",
    features: [
      "130+ GB of video editing assets",
      "Premium software included",
      "Video editing courses",
      "Lifetime access to updates",
    ],
    paymentLink: "upi://pay?pa=paytmqr281005050101159pz7btupdg@paytm&pn=TAPASHI%20ROY&am=99&cu=INR",
  },
  {
    id: 4,
    title: "THE GLOWUP CREED",
    author: "TheSmartStoriesYT",
    description:
      "Join our exclusive community and get access to premium resources, transformative ebooks, and expert self-improvement advice! After purchase, you'll receive exclusive access to our Telegram channel link directly in your email. Plus, get premium editing resources, assets, masterclasses, and much more!",
    originalPrice: 999,
    currentPrice: 399,
    image: "https://envs.sh/MgO.jpg",
    type: "Community",
    rating: 4.9,
    reviews: 80,
    specialOffer: "⚡GET EVERYTHING AT ₹399",
    features: [
      "Exclusive Telegram Channel Access",
      "Community Of Like Minded Brothers",
      "LIFETIME ACCESS",
      "ONETIME PAYMENT",
      "Direct Email Delivery",
    ],
    paymentLink: "upi://pay?pa=paytmqr281005050101159pz7btupdg@paytm&pn=TAPASHI%20ROY&am=399&cu=INR",
  },
  {
    id: 5,
    title: "50,000+ Viral Mega Reels Bundle",
    author: "TheSmartStoriesYT",
    description: "Combo 15+ Reels bundle [LIMITED OFFER]",
    originalPrice: 999,
    currentPrice: 149,
    image: "https://envs.sh/MfQ.jpg",
    backCover: "https://envs.sh/MfD.jpg",
    additionalImage: "https://envs.sh/Mgx.jpg",
    type: "Mega Bundle",
    rating: 4.7,
    reviews: 100,
    specialOffer: "⚡GET EVERYTHING AT ₹149",
    features: ["LIFETIME ACCESS", "Free Bonus worth ₹9000"],
    paymentLink: "upi://pay?pa=paytmqr281005050101159pz7btupdg@paytm&pn=TAPASHI%20ROY&am=149&cu=INR",
  },
  {
    id: 6,
    title: "PROFESSIONAL VIDEO EDITING BUNDLE",
    author: "TheSmartStoriesYT",
    description:
      "AIl In one Video Editing Bundle. Ready to Create Stunning Videos? Dive into the most best Video Editing resources Collection and let your creativity level up!",
    originalPrice: 999,
    currentPrice: 99,
    image: "https://envs.sh/Mf0.jpg",
    backCover: "https://envs.sh/MgO.jpg",
    type: "Video Editing",
    rating: 4.6,
    reviews: 90,
    specialOffer: "⚡GET EVERYTHING AT ₹99",
    features: ["LIFETIME ACCESS", "Free Bonus worth ₹7000", "LIMITED OFFER"],
    paymentLink: "upi://pay?pa=paytmqr281005050101159pz7btupdg@paytm&pn=TAPASHI%20ROY&am=99&cu=INR",
  },
]

